import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import HeaderWrapper from "@/components/HeaderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
        <HeaderWrapper />
          <main>{children}</main>
        </body>
      </html>
  );
}
